name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install libunicorn
      shell: bash
      run: |
        sudo apt update
        sudo apt -y install curl pkg-config
        sudo curl -o /usr/local/lib/libunicorn.so.1 https://bje.id.au/libunicorn.so.1
        sudo curl -o /usr/local/lib/libunicorn.a https://bje.id.au/libunicorn.a
        sudo curl -o /usr/lib/pkgconfig/unicorn.pc https://bje.id.au/unicorn.pc
        sudo ldconfig
    - uses: actions-rs/cargo@v1.0.1
      with:
        command: build
        args: --release
    - uses: actions/upload-artifact@v1
      with:
        name: binary
        path: target/release/rustmtest
    - uses: jaliborc/action-general-autotag@1.0.0
      id: autotag
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        source_file: "Cargo.toml"
        extraction_regex: "\\s*version = \"([\\d\\.]+)\""
    - uses: actions-rs/cargo@v1.0.1
      if: steps.autotag.outputs.tagname != ''
      with:
        command: package
    - name: tarball
      if: steps.autotag.outputs.tagname != ''
      shell: bash
      run: |
        zcf rustmtest-${{ steps.autotag.outputs.tagname }}.tar.bz2 -C target/package rustmtest-${{ steps.autotag.outputs.tagname }}
    - uses: softprops/action-gh-release@v1
      if: steps.autotag.outputs.tagname != ''
      with:
        tag_name: ${{ steps.autotag.outputs.tagname }}
        files: |
          target/release/rustmtest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

