name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install libunicorn
      shell: bash
      run: |
        sudo apt update
        sudo apt -y install curl pkg-config
        sudo curl -o /usr/local/lib/libunicorn.so.1 https://bje.id.au/libunicorn.so.1
        sudo curl -o /usr/local/lib/libunicorn.a https://bje.id.au/libunicorn.a
        sudo curl -o /usr/lib/pkgconfig/unicorn.pc https://bje.id.au/unicorn.pc
        sudo ldconfig
    - uses: actions-rs/cargo@v1.0.1
      with:
        command: build
        args: --release
    - uses: actions/upload-artifact@v1
      with:
        name: binary
        path: target/release/rustmtest

  release:
    needs: build
    runs-on: ubuntu-latest
    #if: contains(github.ref, "/tag/")
    steps:
      - name: Download binary
        uses: actions/download-artifact@v1
        with:
          name: binary
      - name: look at binary
        shell: bash
        run: |
          ls -lR
